# Generated by Django 4.2.1 on 2025-06-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocoa', '0005_tagpost_alter_post_cat_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('month', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='filial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filial', to='cocoa.filial'),
        ),
    ]
