# Generated by Django 4.2.1 on 2025-06-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocoa', '0006_filial_post_filial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='filial',
        ),
        migrations.AddField(
            model_name='tagpost',
            name='filial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filial', to='cocoa.filial'),
        ),
    ]
